In [2]:
import pandas as pd
from pycaret.classification import *

In [3]:
train = pd.DataFrame()
test = pd.DataFrame()

In [1]:
import random
import json

In [8]:
ast = open("ast.json", "r")
json_ast = json.load(ast)

In [16]:
ast_str = ""
for line in json_ast["ast_vec"]:
    ast_str += f"{line}, "

ast_str = ast_str [:-2]

print(ast_str)

DECLARATION, BEGINROOT, int, FUNCTION, BEGINFUNCPARAMS, ENDFUNCPARAMS, STARTFUNCBODY, IDENTIFIER, main, ENDFUNCBODY, ENDROOT, BEGINDECLBODY, BEGINEXPR, DECLARATION, BEGINDECLINIT, BEGINROOT, int, ARRAY, IDENTIFIER, arr[NUMBER, 3], ENDROOT, ENDDECLINIT, BEGINDECLBODY, ENDDECLBODY, ENDEXPR, BEGINEXPR, EXPRSTATEMENT, EQUALS, ARRAYSUBSCRIPTION, IDENTIFIER, arr[NUMBER, 0], =NUMBER, 0, ENDEXPR, BEGINEXPR, EXPRSTATEMENT, EQUALS, ARRAYSUBSCRIPTION, IDENTIFIER, arr[NUMBER, 1], =NUMBER, 2, ENDEXPR, BEGINEXPR, EXPRSTATEMENT, EQUALS, ARRAYSUBSCRIPTION, IDENTIFIER, arr[NUMBER, 2], =NUMBER, 4, ENDEXPR, BEGINEXPR, FOR, BEGINFORPARAMS, DECLARATION, BEGINDECLINIT, BEGINROOT, int, IDENTIFIER, i, ENDROOT, ENDDECLINIT, BEGINDECLBODY, ENDDECLBODY, LESSTHENOREQ, IDENTIFIER, i<=DIV, SIZEOFEXPR, PARENTEXPR, ADDROF, IDENTIFIER, arr/SIZEOF, BEGINROOT, int, ENDROOT, INCREMENT, ++IDENTIFIER, i, ENDFORPARAMS, ENDEXPR, BEGINEXPR, EXPRSTATEMENT, FUNCCALL, IDENTIFIER, printf(STRING, 'test\n'), ENDEXPR, BEGINEXPR, RETURN, NUMBER, 0, ENDEXPR, ENDDECLBODY

In [17]:
ast_vec = []
tree_depth = []
nb_var = []
nb_loops = []
nb_nested_loops = []
nb_leaf = []
algo_vec = []
algo = [0,0,0,0,1,2,3]

for _ in range(10000):
    depth = random.randint(1,200)
    loops = random.randint(0, depth)
    var = random.randint(0, depth)
    nested_loops = random.randint(0, loops)
    leaf = random.randint(depth, depth*4)
    algo_sample = random.randint(1, 210)
    
    ast_vec.append(ast_str)
    tree_depth.append(depth)
    nb_var.append(var)
    nb_loops.append(loops)
    nb_nested_loops.append(nested_loops)
    nb_leaf.append(leaf)
    algo_vec.append(algo_sample)

In [19]:
train["ast_vec"] = ast_vec
train["tree_depth"] = tree_depth
train["nb_var"] = nb_var
train["nb_loops"] = nb_loops
train["nb_nested_loops"] = nb_nested_loops
train["nb_leaf"] = nb_leaf
train["algo_vec"] = algo_vec

In [21]:
tree_depth = []
nb_var = []
nb_loops = []
nb_nested_loops = []
nb_leaf = []
algo_vec = []
algo = [0,0,0,0,1,2,3]

for _ in range(10000):
    depth = random.randint(1,200)
    loops = random.randint(0, depth)
    var = random.randint(0, depth)
    nested_loops = random.randint(0, loops)
    leaf = random.randint(depth, depth*4)
    algo_sample = random.randint(1, 210)
    
    tree_depth.append(depth)
    nb_var.append(var)
    nb_loops.append(loops)
    nb_nested_loops.append(nested_loops)
    nb_leaf.append(leaf)
    algo_vec.append(algo_sample)

In [22]:
test["ast_vec"] = ast_vec
test["tree_depth"] = tree_depth
test["nb_var"] = nb_var
test["nb_loops"] = nb_loops
test["nb_nested_loops"] = nb_nested_loops
test["nb_leaf"] = nb_leaf
test["algo_vec"] = algo_vec

In [23]:
train

,tree_depth,nb_var,nb_loops,nb_nested_loops,nb_leaf,algo_vec,ast_vec
0,39,29,14,13,144,205,"DECLARATION, BEGINROOT, int, FUNCTION, BEGINFU..."
1,183,169,99,71,497,136,"DECLARATION, BEGINROOT, int, FUNCTION, BEGINFU..."
2,141,108,128,44,293,209,"DECLARATION, BEGINROOT, int, FUNCTION, BEGINFU..."
3,77,34,20,5,228,124,"DECLARATION, BEGINROOT, int, FUNCTION, BEGINFU..."
4,19,8,8,1,41,74,"DECLARATION, BEGINROOT, int, FUNCTION, BEGINFU..."
...,...,...,...,...,...,...,...
9995,109,100,13,9,218,17,"DECLARATION, BEGINROOT, int, FUNCTION, BEGINFU..."
9996,70,41,43,38,125,61,"DECLARATION, BEGINROOT, int, FUNCTION, BEGINFU..."
9997,29,25,0,0,102,170,"DECLARATION, BEGINROOT, int, FUNCTION, BEGINFU..."
9998,121,49,25,22,180,127,"DECLARATION, BEGINROOT, int, FUNCTION, BEGINFU..."
9999,119,29,103,95,137,68,"DECLARATION, BEGINROOT, int, FUNCTION, BEGINFU..."

## Dataframes are built

In [24]:
s = setup(train, target = 'algo_vec')

In [25]:
best = compare_models()

In [26]:
evaluate_model(best)

interactive(children=(ToggleButtons(description='Plot Type:', icons=('',), options=(('Hyperparameters', 'paramâ€¦

In [27]:
save_model(best, 'best_pipeline')

Transformation Pipeline and Model Successfully Saved

(Pipeline(memory=None,
          steps=[('dtypes',
                  DataTypes_Auto_infer(categorical_features=[],
                                       display_types=True, features_todrop=[],
                                       id_columns=[],
                                       ml_usecase='classification',
                                       numerical_features=[], target='algo_vec',
                                       time_features=[])),
                 ('imputer',
                  Simple_Imputer(categorical_strategy='not_available',
                                 fill_value_categorical=None,
                                 fill_value_numerical=None,
                                 numeric_str...
                 ('fix_perfect', Remove_100(target='algo_vec')),
                 ('clean_names', Clean_Colum_Names()),
                 ('feature_select', 'passthrough'), ('fix_multi', 'passthrough'),
                 ('dfs', 'passthrough'), ('pca', 'passthrough'),
                 ['trained_model',
                  RidgeClassifier(alpha=1.0, class_weight=None, copy_X=True,
                                  fit_intercept=True, max_iter=None,
                                  normalize=False, random_state=3497,
                                  solver='auto', tol=0.001)]],
          verbose=False),
 'best_pipeline.pkl')

In [ ]:
loaded_model = load_model('my_best_pipeline')
print(loaded_model)