In [1]:
import pandas as pd
from pycaret.classification import *

In [2]:
train = pd.DataFrame()
test = pd.DataFrame()

In [3]:
import random

In [4]:
tree_depth = []
nb_var = []
nb_loops = []
nb_nested_loops = []
nb_leaf = []
algo_vec = []
algo = [0,0,0,0,1,2,3]

for _ in range(10000):
    depth = random.randint(1,200)
    loops = random.randint(0, depth)
    var = random.randint(0, depth)
    nested_loops = random.randint(0, loops)
    leaf = random.randint(depth, depth*4)
    algo_sample = random.randint(1, 210)
    
    tree_depth.append(depth)
    nb_var.append(var)
    nb_loops.append(loops)
    nb_nested_loops.append(nested_loops)
    nb_leaf.append(leaf)
    algo_vec.append(algo_sample)

In [5]:
train["tree_depth"] = tree_depth
train["nb_var"] = nb_var
train["nb_loops"] = nb_loops
train["nb_nested_loops"] = nb_nested_loops
train["nb_leaf"] = nb_leaf
train["algo_vec"] = algo_vec

In [6]:
tree_depth = []
nb_var = []
nb_loops = []
nb_nested_loops = []
nb_leaf = []
algo_vec = []
algo = [0,0,0,0,1,2,3]

for _ in range(10000):
    depth = random.randint(1,200)
    loops = random.randint(0, depth)
    var = random.randint(0, depth)
    nested_loops = random.randint(0, loops)
    leaf = random.randint(depth, depth*4)
    algo_sample = random.randint(1, 210)
    
    tree_depth.append(depth)
    nb_var.append(var)
    nb_loops.append(loops)
    nb_nested_loops.append(nested_loops)
    nb_leaf.append(leaf)
    algo_vec.append(algo_sample)

In [7]:
test["tree_depth"] = tree_depth
test["nb_var"] = nb_var
test["nb_loops"] = nb_loops
test["nb_nested_loops"] = nb_nested_loops
test["nb_leaf"] = nb_leaf
test["algo_vec"] = algo_vec

In [9]:
train

      tree_depth  nb_var  nb_loops  nb_nested_loops  nb_leaf  algo_vec
0            115     111        70               57      264        93
1            146     108        73               71      238       144
2             38       5        24               24       85        78
3             55      46        17                7      112        23
4             67      59        52               33      129       150
...          ...     ...       ...              ...      ...       ...
9995         153     149        55                3      407       114
9996         180      14        34               12      388        99
9997         143     122       122               57      225       119
9998         102      38        37               29      175        23
9999         139      12        89               59      452       151

[10000 rows x 6 columns]

## Dataframes are built

In [10]:
s = setup(train, target = 'algo_vec')

In [11]:
best = compare_models()

In [ ]:
evaluate_model(best)